input {
  beats {
    port => 5044
  }
}

filter {
  # Add default categorization based on Filebeat tags
  if ![category] {
    if "evtx" in [tags] {
      mutate { add_field => { "category" => "system-logs" } }
    } else if "syslog" in [tags] {
      mutate { add_field => { "category" => "system-logs" } }
    } else if "sqlite" in [tags] {
      mutate { add_field => { "category" => "browser-history" } }
    } else {
      mutate { add_field => { "category" => "unknown-artifact" } }
    }
  }

  # If the message is a JSON string, try to parse it
  if [message] =~ /^{.*}$/ {
    json {
      source => "message"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "dfir-%{category}-%{+YYYY.MM.dd}"
  }
  # Standard out for docker logs and debugging
  stdout { codec => rubydebug }
}
